site_name: "Good Enough Rules: ScriptAnalyzer Rules Module"
repo_url: https://github.com/HeyItsGilbert/GoodEnoughRules
theme: readthedocs
nav:
  - Home: 'index.md'
  - Changelog: 'https://github.com/HeyItsGilbert/GoodEnoughRules/blob/main/CHANGELOG.md'
  - en-US:
      - en-US/
plugins:
  - search
  - include_dir_to_nav
