name: Publish Module
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Publish:
    uses: HeyItsGilbert/.github/.github/workflows/PublishModule.yml@main
    secrets: inherit
